

planet:
  surface-gravity: 980.7 # cm/s2
  fscale: 1.0
  surface-albedo: 0.25
  tropopause-altitude: 1.1e6 # cm
  planet-radius: 6.371e8 # cm
  surface-pressure: 1.013 # bar

settings:
  diurnal-averaging-factor: 0.5
  lgrid: 0
  io2: 2
  ino: 0
  epsj: 1.0e-9
  lightning-dissipation-rate: 9.8019e-9 # power dissipated divided by planet area [Watts/cm^2]
  frak: 1
  hcdens: 0.63
  ihztype: 0
  solar-zenith-angle: 50.0
  lightning: true
  rainout-on: true
  condensation-factor: 1.6e-5 # not sure what this is
  relative-humidity-cold-trap: 0.1
  relative-humidity: manabe # can be manabe or a number between 0 and 1
  number-layers: 200
  top-atmosphere: 100.0e5
  bottom-atmosphere: 0.0
  